# Generated by Django 4.0.1 on 2024-05-06 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agendamentos', '0003_historicodeagendamento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Barbearia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_da_barbearia', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome da barbearia')),
                ('cnpj', models.CharField(blank=True, max_length=14, null=True, verbose_name='CNPJ')),
                ('servicos', models.ManyToManyField(blank=True, to='agendamentos.Servico', verbose_name='Serviços')),
            ],
            options={
                'verbose_name': 'Barbearia',
                'verbose_name_plural': 'Barbearias',
            },
        ),
    ]
