# Generated by Django 4.0.1 on 2024-05-06 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbearias', '0002_remove_barbearia_servicos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barbearia',
            name='cnpj',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='CNPJ'),
        ),
    ]
