# Generated by Django 4.0.1 on 2024-05-07 11:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('barbearias', '0005_alter_avaliacao_avaliacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='barbearia',
            name='dono',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='barbearias', to=settings.AUTH_USER_MODEL, verbose_name='Dono'),
        ),
        migrations.AddField(
            model_name='barbearia',
            name='funcionarios',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='Funcionários'),
        ),
    ]
