# Generated by Django 4.0.1 on 2024-05-07 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbearias', '0006_barbearia_dono_barbearia_funcionarios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barbearia',
            name='cnpj',
            field=models.CharField(blank=True, max_length=19, null=True, verbose_name='CNPJ'),
        ),
    ]
