# Generated by Django 4.0.1 on 2024-05-08 15:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('agendamentos', '0006_remove_agendamento_servico_agendamento_servico'),
        ('barbearias', '0007_alter_barbearia_cnpj'),
    ]

    operations = [
        migrations.CreateModel(
            name='Barbeiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barbearia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='barbearias.barbearia', verbose_name='Barbearia')),
                ('barbeiro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='barbeiro', to=settings.AUTH_USER_MODEL, verbose_name='Barbeiro')),
                ('servicos', models.ManyToManyField(blank=True, to='agendamentos.Servico', verbose_name='Serviços')),
            ],
            options={
                'verbose_name': 'Barbeiro',
                'verbose_name_plural': 'Barbeiros',
            },
        ),
    ]
