# Generated by Django 4.0.1 on 2024-05-08 20:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('barbearias', '0009_alter_barbeiro_barbeiro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barbeiro',
            name='barbeiro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='barbeiro', to=settings.AUTH_USER_MODEL, verbose_name='Barbeiro'),
        ),
    ]
