# Generated by Django 4.0.1 on 2024-05-09 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbearias', '0010_alter_barbeiro_barbeiro'),
    ]

    operations = [
        migrations.AddField(
            model_name='barbearia',
            name='bairro',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Bairro'),
        ),
        migrations.AddField(
            model_name='barbearia',
            name='cep',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='CEP'),
        ),
        migrations.AddField(
            model_name='barbearia',
            name='cidade',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Cidade'),
        ),
        migrations.AddField(
            model_name='barbearia',
            name='complemento',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Complemento'),
        ),
        migrations.AddField(
            model_name='barbearia',
            name='estado',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='barbearia',
            name='rua',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Rua'),
        ),
    ]
