# Generated by Django 4.0.1 on 2024-05-16 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbearias', '0011_barbearia_bairro_barbearia_cep_barbearia_cidade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='barbeiro',
            name='freelancer',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Barbeiro Freelancer'),
        ),
    ]
