# Generated by Django 4.0.1 on 2024-05-16 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbearias', '0012_barbeiro_freelancer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barbeiro',
            name='freelancer',
            field=models.BooleanField(default=False, verbose_name='Barbeiro Freelancer'),
        ),
    ]
