# Generated by Django 4.0.1 on 2024-05-16 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbearias', '0013_alter_barbeiro_freelancer'),
    ]

    operations = [
        migrations.AddField(
            model_name='barbearia',
            name='agendamentos',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Agendamentos'),
        ),
    ]
