# Generated by Django 4.0.1 on 2024-05-16 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbearias', '0014_barbearia_agendamentos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barbearia',
            name='agendamentos',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Agendamentos'),
        ),
    ]
