# Generated by Django 4.0.1 on 2024-05-18 22:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbearias', '0018_remove_barbearia_agendamentos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contato', models.CharField(blank=True, max_length=100, null=True, verbose_name='Contato')),
                ('link_para_contato', models.URLField(blank=True, max_length=100, null=True, verbose_name='Link para contato')),
                ('barbearia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contatos', to='barbearias.barbearia', verbose_name='Barbearia')),
            ],
            options={
                'verbose_name': 'Contato',
                'verbose_name_plural': 'Contatos',
            },
        ),
    ]
