# Generated by Django 4.0.1 on 2024-06-03 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('barbearias', '0022_alter_avaliacao_avaliacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Financeiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('renda_semanal', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Renda semanal')),
                ('renda_mensal', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Renda mensal')),
                ('despesas', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Despesas')),
                ('lucro_total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Lucro total')),
                ('barbearia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='barbearias.barbearia', verbose_name='Barbearia')),
            ],
        ),
    ]
