# Generated by Django 4.0.1 on 2024-06-03 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbearias', '0023_financeiro'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='financeiro',
            options={'verbose_name': 'Finança', 'verbose_name_plural': 'Finanças'},
        ),
        migrations.AddField(
            model_name='financeiro',
            name='receita_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Receita total'),
        ),
    ]
