# Generated by Django 4.0.1 on 2024-06-03 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbearias', '0024_alter_financeiro_options_financeiro_receita_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='barbeiro',
            name='salario',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Salário'),
        ),
    ]
