# Generated by Django 4.0.1 on 2024-06-04 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbearias', '0026_remove_financeiro_renda_semanal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financeiro',
            name='despesas',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Salários, produtos etc...', max_digits=10, null=True, verbose_name='Despesas'),
        ),
        migrations.AlterField(
            model_name='financeiro',
            name='renda_mensal',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Seu Lucro do mês', max_digits=10, null=True, verbose_name='Renda mensal'),
        ),
    ]
