# Generated by Django 4.0.1 on 2024-06-04 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbearias', '0027_alter_financeiro_despesas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='financeiro',
            name='lucro',
            field=models.BooleanField(default=False, verbose_name='Lucro'),
        ),
        migrations.AddField(
            model_name='financeiro',
            name='prejuizo',
            field=models.BooleanField(default=False, verbose_name='Prejuízo'),
        ),
    ]
