# Generated by Django 4.0.1 on 2024-06-07 20:04

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('barbearias', '0028_financeiro_lucro_financeiro_prejuizo'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanosDeFidelidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome')),
                ('beneficios', tinymce.models.HTMLField(blank=True, null=True, verbose_name='Beneficios')),
                ('preco', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Preço por mês')),
                ('quantidade_de_cortes', models.PositiveIntegerField(blank=True, null=True, verbose_name='Quantidade de cortes')),
                ('usuarios', models.PositiveIntegerField(blank=True, null=True, verbose_name='Quantidade de usuários que possuem esse plano')),
                ('barbearia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='barbearias.barbearia', verbose_name='Barbearia')),
            ],
            options={
                'verbose_name': 'Plano de fidelidade',
                'verbose_name_plural': 'Planos de fidelidade',
            },
        ),
    ]
