# Generated by Django 4.0.1 on 2024-06-08 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbearias', '0030_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='financeiro',
            name='lucro_planos',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Lucro dos planos de fidelidade'),
        ),
    ]
