# Generated by Django 4.0.1 on 2024-06-09 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbearias', '0031_financeiro_lucro_planos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planosdefidelidade',
            name='preco',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Mensalidade'),
        ),
    ]
