# Generated by Django 4.0.1 on 2024-06-09 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbearias', '0034_alter_financeiro_barbearia'),
    ]

    operations = [
        migrations.AddField(
            model_name='planosdefidelidade',
            name='atualizado_em',
            field=models.DateField(auto_now=True, null=True, verbose_name='Atualizado em'),
        ),
        migrations.AddField(
            model_name='planosdefidelidade',
            name='criado_em',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Criado em'),
        ),
    ]
