# Generated by Django 4.0.1 on 2024-06-10 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('barbearias', '0035_planosdefidelidade_atualizado_em_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planosdefidelidade',
            name='atualizado_em',
        ),
        migrations.RemoveField(
            model_name='planosdefidelidade',
            name='criado_em',
        ),
    ]
