# Generated by Django 4.0.1 on 2024-06-10 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbearias', '0036_remove_planosdefidelidade_atualizado_em_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='barbearia',
            name='horario_de_abertura',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Horário de abertura'),
        ),
        migrations.AddField(
            model_name='barbearia',
            name='horario_de_fechamento',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Horário de fechamento'),
        ),
    ]
