# Generated by Django 4.0.1 on 2024-06-15 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbearias', '0038_barbearia_tipo_de_barbearia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barbearia',
            name='horario_de_abertura',
            field=models.TimeField(blank=True, null=True, verbose_name='Horário de abertura'),
        ),
        migrations.AlterField(
            model_name='barbearia',
            name='horario_de_fechamento',
            field=models.TimeField(blank=True, null=True, verbose_name='Horário de fechamento'),
        ),
    ]
