# Generated by Django 4.0.1 on 2024-06-15 20:04

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('barbearias', '0039_alter_barbearia_horario_de_abertura_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='planosdefidelidade',
            name='cor_do_cartao',
            field=colorfield.fields.ColorField(blank=True, default='#808080', image_field=None, max_length=25, null=True, samples=None, verbose_name='Cor do cartão'),
        ),
    ]
