# Generated by Django 4.0.1 on 2024-06-16 22:18

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('barbearias', '0041_barbeiro_avaliacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvaliacaoDoBarbeiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avaliacao', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Avaliação do barbeiro')),
                ('barbeiro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='barbeiro_avaliacao', to='barbearias.barbeiro', verbose_name='Barbeiro')),
            ],
            options={
                'verbose_name': 'Avaliação do barbeiro',
                'verbose_name_plural': 'Avaliações do barbeiro',
            },
        ),
    ]
