# Generated by Django 4.0.1 on 2024-06-17 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbearias', '0043_financeiro_lucro_mes_anterior'),
    ]

    operations = [
        migrations.AddField(
            model_name='financeiro',
            name='comparar_lucros_mes_anterior_e_atual',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Lucro do mês anterior em comparação ao atual'),
        ),
    ]
