# Generated by Django 4.0.1 on 2024-06-23 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbearias', '0045_alter_financeiro_comparar_lucros_mes_anterior_e_atual'),
    ]

    operations = [
        migrations.AddField(
            model_name='barbearia',
            name='data_de_atualizacao',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Data de atualização'),
        ),
        migrations.AddField(
            model_name='barbearia',
            name='data_de_criacao',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Data de criação'),
        ),
    ]
