# Generated by Django 4.0.1 on 2024-06-23 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbearias', '0046_barbearia_data_de_atualizacao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='financeiro',
            name='comparar_lucros_mes_anterior_e_atual_porcentagem',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Lucro do mês atual em comparação ao anterior(Porcentagem)'),
        ),
    ]
