# Generated by Django 4.0.1 on 2024-06-26 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbearias', '0047_financeiro_comparar_lucros_mes_anterior_e_atual_porcentagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='credito',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Pode ser utilizado para obter desconto nos serviços', max_digits=10, null=True, verbose_name='Crédito que cliente possue'),
        ),
    ]
