# Generated by Django 4.0.1 on 2024-06-28 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbearias', '0049_alter_cliente_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='avaliacao',
            name='comentario',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Comentário'),
        ),
    ]
