# Generated by Django 4.0.1 on 2024-06-29 22:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('barbearias', '0052_remove_funcionario_data_de_admissao'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='barbearia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='barbearias.barbearia', verbose_name='Barbearia'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='salario',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Salário'),
        ),
    ]
