# Generated by Django 4.0.1 on 2024-07-03 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbearias', '0053_funcionario_barbearia_funcionario_salario'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='clt',
            field=models.BooleanField(default=False, verbose_name='CLT'),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='pj',
            field=models.BooleanField(default=False, verbose_name='Pessoa Jurídica'),
        ),
    ]
