# Generated by Django 4.0.1 on 2024-07-06 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbearias', '0054_funcionario_clt_funcionario_pj'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='cpf',
            field=models.CharField(max_length=14, unique=True, verbose_name='CPF'),
        ),
    ]
