# Generated by Django 4.0.1 on 2024-07-08 19:54

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbearias', '0056_alter_barbearia_funcionarios'),
    ]

    operations = [
        migrations.AddField(
            model_name='barbearia',
            name='media_das_avaliacoes',
            field=models.DecimalField(blank=True, decimal_places=1, default=Decimal('0.0'), max_digits=5, null=True, verbose_name='Média das avaliações'),
        ),
    ]
