# Generated by Django 4.0.1 on 2024-07-12 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbearias', '0057_barbearia_media_das_avaliacoes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='barbeiro',
            name='barbearia',
        ),
        migrations.AddField(
            model_name='barbeiro',
            name='barbearias',
            field=models.ManyToManyField(to='barbearias.Barbearia', verbose_name='Barbearia que o barbeiro trabalha'),
        ),
    ]
