# Generated by Django 4.0.1 on 2024-07-13 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('barbearias', '0059_barbearia_barbeiros'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financeiro',
            name='barbearia',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='barbearias.barbearia', verbose_name='Barbearia'),
            preserve_default=False,
        ),
    ]
