# Generated by Django 4.0.1 on 2024-07-13 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbearias', '0060_alter_financeiro_barbearia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barbearia',
            name='barbeiros',
            field=models.ManyToManyField(blank=True, to='barbearias.Barbeiro', verbose_name='Barbeiros'),
        ),
    ]
