# Generated by Django 4.0.1 on 2024-07-14 18:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('barbearias', '0061_alter_barbearia_barbeiros'),
    ]

    operations = [
        migrations.AddField(
            model_name='barbearia',
            name='usuario_de_atualizacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuario_atualizacao', to=settings.AUTH_USER_MODEL, verbose_name='Usuário de atualização'),
        ),
        migrations.AddField(
            model_name='barbearia',
            name='usuario_de_criacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuario_criacao', to=settings.AUTH_USER_MODEL, verbose_name='Usuário de criação'),
        ),
    ]
