# Generated by Django 4.0.1 on 2024-07-14 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbearias', '0062_barbearia_usuario_de_atualizacao_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetodoDePagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metodo_de_pagamento', models.CharField(max_length=100, verbose_name='Método de pagamento')),
            ],
            options={
                'verbose_name': 'Método de Pagamento',
                'verbose_name_plural': 'Métodos de Pagamento',
            },
        ),
        migrations.AddField(
            model_name='planosdefidelidade',
            name='metodo_de_pagamento',
            field=models.ManyToManyField(blank=True, to='barbearias.MetodoDePagamento', verbose_name='Método de pagamento'),
        ),
    ]
