# Generated by Django 4.0.1 on 2024-07-14 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbearias', '0064_chavepix_cartao'),
    ]

    operations = [
        migrations.AddField(
            model_name='chavepix',
            name='chave_aleatoria',
            field=models.BooleanField(default=False, verbose_name='Chave aleatória'),
        ),
    ]
