# Generated by Django 4.0.1 on 2024-07-17 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbearias', '0065_chavepix_chave_aleatoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planosdefidelidade',
            name='metodo_de_pagamento',
            field=models.ManyToManyField(blank=True, to='barbearias.MetodoDePagamento', verbose_name='Método de pagamento aceitáveis'),
        ),
    ]
