# Generated by Django 4.0.1 on 2024-07-17 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbearias', '0066_alter_planosdefidelidade_metodo_de_pagamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planosdefidelidade',
            name='metodo_de_pagamento',
            field=models.ManyToManyField(blank=True, to='barbearias.MetodoDePagamento', verbose_name='Métodos de pagamento aceitáveis'),
        ),
    ]
