# Generated by Django 4.0.1 on 2024-07-25 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbearias', '0068_barbearia_metodo_de_pagamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='chavepix',
            name='cpf_cnpj',
            field=models.BooleanField(default=False, verbose_name='CPF/CNPJ'),
        ),
        migrations.AddField(
            model_name='chavepix',
            name='telefone',
            field=models.BooleanField(default=False, verbose_name='Telefone'),
        ),
    ]
