# Generated by Django 4.0.1 on 2024-07-26 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('barbearias', '0069_chavepix_cpf_cnpj_chavepix_telefone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planosdefidelidade',
            name='barbearia',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='barbearias.barbearia', verbose_name='Barbearia'),
            preserve_default=False,
        ),
    ]
