# Generated by Django 4.0.1 on 2024-07-28 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbearias', '0071_alter_chavepix_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartao',
            name='cartao_bloqueado',
            field=models.BooleanField(default=False, verbose_name='Cartão bloqueado'),
        ),
    ]
