# Generated by Django 4.0.1 on 2024-08-02 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('barbearias', '0072_cartao_cartao_bloqueado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartao',
            name='titular',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='barbearias.cliente', verbose_name='Titular do cartão'),
        ),
    ]
