# Generated by Django 4.0.1 on 2024-08-03 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbearias', '0073_alter_cartao_titular'),
    ]

    operations = [
        migrations.AddField(
            model_name='financeiro',
            name='lucro_produtos',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Lucro dos produtos'),
        ),
    ]
