# Generated by Django 4.0.1 on 2024-08-04 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('barbearias', '0074_financeiro_lucro_produtos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planosdefidelidade',
            name='quantidade_de_cortes',
        ),
    ]
