# Generated by Django 4.0.1 on 2024-08-31 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('barbearias', '0075_remove_planosdefidelidade_quantidade_de_cortes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financeiro',
            name='barbearia',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='barbearias.barbearia', verbose_name='Barbearia'),
        ),
    ]
