version: '3'

services:
  backend:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./front:/app/front
