# Generated by Django 4.0.1 on 2024-05-06 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('barbearias', '0002_remove_barbearia_servicos'),
        ('agendamentos', '0004_agendamento_preco_do_servico'),
    ]

    operations = [
        migrations.AddField(
            model_name='servico',
            name='disponivel_na_barbearia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='barbearias.barbearia', verbose_name='Barbearia'),
        ),
    ]
