# Generated by Django 4.0.1 on 2024-05-07 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0005_servico_disponivel_na_barbearia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agendamento',
            name='servico',
        ),
        migrations.AddField(
            model_name='agendamento',
            name='servico',
            field=models.ManyToManyField(blank=True, to='agendamentos.Servico', verbose_name='Serviço'),
        ),
    ]
