# Generated by Django 4.0.1 on 2024-05-12 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0007_remove_agendamento_servico_agendamento_servico'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicodeagendamento',
            name='preco_do_servico',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Preço do serviço'),
        ),
    ]
