# Generated by Django 4.0.1 on 2024-05-23 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0008_historicodeagendamento_preco_do_servico'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agendamento',
            name='servico',
        ),
        migrations.AddField(
            model_name='agendamento',
            name='servico',
            field=models.ManyToManyField(blank=True, help_text='Você pode escolher mais de um serviço', to='agendamentos.Servico', verbose_name='Serviço'),
        ),
    ]
