# Generated by Django 4.0.1 on 2024-05-25 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0009_remove_agendamento_servico_agendamento_servico'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agendamento',
            name='servico',
        ),
        migrations.AddField(
            model_name='agendamento',
            name='servico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='agendamentos.servico', verbose_name='Serviço'),
        ),
    ]
