# Generated by Django 4.0.1 on 2024-05-25 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0010_remove_agendamento_servico_agendamento_servico'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='numero_do_agendamento',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Número do agendamento'),
        ),
    ]
