# Generated by Django 4.0.1 on 2024-06-13 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0012_meuagendamento'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaDoServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Categoria do Serviço',
                'verbose_name_plural': 'Categorias dos Serviços',
            },
        ),
    ]
