# Generated by Django 4.0.1 on 2024-06-14 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0015_meuagendamento_cancelar_agendamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='agendamento_cancelado',
            field=models.BooleanField(default=False, verbose_name='Agendamento cancelado'),
        ),
    ]
