# Generated by Django 4.0.1 on 2024-06-15 18:22

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0016_agendamento_agendamento_cancelado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servico',
            name='descricao',
            field=tinymce.models.HTMLField(blank=True, help_text='Você também pode adicionar imagens na descrição', null=True, verbose_name='Descrição'),
        ),
    ]
