# Generated by Django 4.0.1 on 2024-06-27 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('barbearias', '0049_alter_cliente_cliente'),
        ('agendamentos', '0017_alter_servico_descricao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agendamento',
            name='usuario',
        ),
        migrations.AddField(
            model_name='agendamento',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='barbearias.cliente', verbose_name='Usuário'),
        ),
        migrations.AddField(
            model_name='agendamento',
            name='desconto_do_usuario',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Desconto atráves do crédito do cliente'),
        ),
    ]
