# Generated by Django 4.0.1 on 2024-06-27 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('barbearias', '0049_alter_cliente_cliente'),
        ('agendamentos', '0018_remove_agendamento_usuario_agendamento_cliente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicodeagendamento',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='barbearias.cliente', verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='meuagendamento',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='barbearias.cliente', verbose_name='Cliente'),
        ),
    ]
