# Generated by Django 4.0.1 on 2024-08-31 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0019_alter_historicodeagendamento_cliente_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servico',
            name='tempo_de_duracao',
        ),
    ]
