# Generated by Django 4.0.1 on 2024-09-14 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0021_servico_tempo_de_duracao_minutos'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='passou_da_data',
            field=models.BooleanField(default=False, verbose_name='Passou da data marcada'),
        ),
    ]
