# Generated by Django 4.0.1 on 2024-05-08 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='tipo_usuario',
            field=models.CharField(choices=[('Barbeiro', 'Barbeiro'), ('Cliente', 'Cliente')], default='Cliente', max_length=10, verbose_name='Tipo de Usuário'),
        ),
    ]
