# Generated by Django 4.0.1 on 2024-05-08 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_profile_tipo_usuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='tipo_usuario',
            new_name='tipo_do_usuario',
        ),
    ]
