# Generated by Django 4.0.1 on 2024-05-08 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_rename_tipo_usuario_profile_tipo_do_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='tipo_do_usuario',
            field=models.CharField(blank=True, choices=[('Barbeiro', 'Barbeiro'), ('Cliente', 'Cliente')], default='Cliente', max_length=10, null=True, verbose_name='Tipo de Usuário'),
        ),
    ]
