# Generated by Django 4.0.1 on 2024-05-11 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilidades', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aviso',
            options={'verbose_name': 'Aviso', 'verbose_name_plural': 'Avisos'},
        ),
        migrations.AlterField(
            model_name='aviso',
            name='data_de_encerramento',
            field=models.DateField(blank=True, null=True, verbose_name='Data de encerramento'),
        ),
        migrations.AlterField(
            model_name='aviso',
            name='data_de_inicio',
            field=models.DateField(blank=True, null=True, verbose_name='Data de início'),
        ),
    ]
