# Generated by Django 4.0.1 on 2024-05-16 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilidades', '0002_alter_aviso_options_alter_aviso_data_de_encerramento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aviso',
            name='aviso',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Aviso'),
        ),
    ]
