# Generated by Django 4.0.1 on 2024-05-25 22:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0011_agendamento_numero_do_agendamento'),
        ('utilidades', '0003_aviso_aviso'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promocao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_da_promocao', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome da promoção')),
                ('inicio_da_promocao', models.DateField(blank=True, null=True, verbose_name='Início da promoção')),
                ('fim_da_promocao', models.DateField(blank=True, null=True, verbose_name='Fim da promoção')),
                ('servico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='agendamentos.servico', verbose_name='Serviço')),
            ],
            options={
                'verbose_name': 'Promoção',
                'verbose_name_plural': 'Promoções',
            },
        ),
    ]
