# Generated by Django 4.0.1 on 2024-06-12 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('barbearias', '0038_barbearia_tipo_de_barbearia'),
        ('utilidades', '0004_promocao'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocao',
            name='plano_fidelidade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='barbearias.planosdefidelidade', verbose_name='Plano de fidelidade'),
        ),
    ]
