# Generated by Django 4.0.1 on 2024-08-02 20:39

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0019_alter_historicodeagendamento_cliente_and_more'),
        ('utilidades', '0005_promocao_plano_fidelidade'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço')),
                ('quantidade', models.PositiveIntegerField(default=0, verbose_name='Quantidade')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('descricao', tinymce.models.HTMLField(blank=True, null=True, verbose_name='Descrição/Instruções')),
                ('data_de_criacao', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Data de criação')),
                ('data_de_atualizacao', models.DateTimeField(auto_now=True, null=True, verbose_name='Data de atualização')),
                ('tipo_do_produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='agendamentos.categoriadoservico', verbose_name='Tipo do produto')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
            },
        ),
    ]
