# Generated by Django 4.0.1 on 2024-08-03 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('barbearias', '0074_financeiro_lucro_produtos'),
        ('utilidades', '0006_produto'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='barbearia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='barbearias.barbearia', verbose_name='Barbearia'),
        ),
    ]
