# Generated by Django 4.0.1 on 2024-08-11 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('barbearias', '0075_remove_planosdefidelidade_quantidade_de_cortes'),
        ('utilidades', '0007_produto_barbearia'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotaFiscal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(max_length=14, unique=True, verbose_name='CPF do comprador')),
                ('numero', models.CharField(max_length=100, verbose_name='Número')),
                ('data_emissao', models.DateField(verbose_name='Data de emissão')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='barbearias.cliente', verbose_name='Cliente')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='utilidades.produto', verbose_name='Produto')),
            ],
            options={
                'verbose_name': 'Nota Fiscal',
                'verbose_name_plural': 'Notas Fiscais',
            },
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(help_text='Quantidade de unidades do produto', verbose_name='Quantidade')),
                ('preco_total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço total')),
                ('data_da_compra', models.DateField(auto_now_add=True, verbose_name='Data da compra')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='barbearias.cliente', verbose_name='Cliente')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='utilidades.produto', verbose_name='Produto')),
            ],
            options={
                'verbose_name': 'Compra',
                'verbose_name_plural': 'Compras',
            },
        ),
    ]
