# Generated by Django 4.0.1 on 2024-08-11 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utilidades', '0009_notafiscal_valor_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notafiscal',
            name='cpf',
        ),
    ]
