# Generated by Django 4.0.1 on 2024-08-11 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilidades', '0010_remove_notafiscal_cpf'),
    ]

    operations = [
        migrations.AddField(
            model_name='notafiscal',
            name='quantidade_comprada',
            field=models.PositiveIntegerField(default=0, verbose_name='Quantidade comprada'),
        ),
    ]
