# Generated by Django 4.0.1 on 2024-08-17 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilidades', '0011_notafiscal_quantidade_comprada'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compra',
            name='produto',
        ),
        migrations.AddField(
            model_name='compra',
            name='produto',
            field=models.ManyToManyField(blank=True, to='utilidades.Produto', verbose_name='Produto'),
        ),
    ]
