# Generated by Django 4.0.1 on 2024-08-17 21:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utilidades', '0012_remove_compra_produto_compra_produto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compra',
            name='produto',
        ),
        migrations.AddField(
            model_name='compra',
            name='produto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='utilidades.produto', verbose_name='Produto'),
        ),
    ]
