# Generated by Django 4.0.1 on 2024-08-17 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utilidades', '0013_remove_compra_produto_compra_produto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='produto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='utilidades.produto', verbose_name='Produto'),
        ),
    ]
