# Generated by Django 4.0.1 on 2024-08-17 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilidades', '0014_alter_compra_produto'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='preco_unitario',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Preço unitário'),
        ),
    ]
