# Generated by Django 4.0.1 on 2024-08-17 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilidades', '0015_compra_preco_unitario'),
    ]

    operations = [
        migrations.AddField(
            model_name='notafiscal',
            name='valor_unitario',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Valor unitário'),
        ),
    ]
