# Generated by Django 4.0.1 on 2024-08-23 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilidades', '0017_notafiscal_barbearia_notafiscal_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='status',
            field=models.CharField(blank=True, choices=[('Pendente', 'Pendente'), ('Em andamento', 'Em andamento'), ('Cancelada', 'Cancelada'), ('Preparando envio', 'Preparando envio'), ('Enviada', 'Enviada'), ('A caminho', 'A caminho'), ('Entregue', 'Entregue')], default='Pendente', max_length=20, null=True, verbose_name='Status'),
        ),
    ]
