# Generated by Django 4.0.1 on 2024-08-24 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utilidades', '0018_compra_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='notafiscal',
            name='compra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='utilidades.compra', verbose_name='Compra'),
        ),
    ]
