# Generated by Django 4.0.1 on 2024-08-24 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utilidades', '0019_notafiscal_compra'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notafiscal',
            name='compra',
        ),
        migrations.AddField(
            model_name='compra',
            name='nota_fiscal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='utilidades.notafiscal', verbose_name='Nota Fiscal'),
        ),
        migrations.AddField(
            model_name='notafiscal',
            name='compra_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='utilidades.compra', verbose_name='Compra'),
        ),
    ]
