# Generated by Django 4.0.1 on 2024-08-24 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utilidades', '0020_remove_notafiscal_compra_compra_nota_fiscal_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notafiscal',
            name='compra_id',
        ),
        migrations.AddField(
            model_name='notafiscal',
            name='compra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notafiscal_compra', to='utilidades.compra', verbose_name='Compra'),
        ),
        migrations.AlterField(
            model_name='compra',
            name='nota_fiscal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='compra_notafiscal', to='utilidades.notafiscal', verbose_name='Nota Fiscal'),
        ),
    ]
