# Generated by Django 4.0.1 on 2024-08-24 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilidades', '0021_remove_notafiscal_compra_id_notafiscal_compra_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='quantidade_total_vendida',
            field=models.PositiveBigIntegerField(blank=True, default=0, null=True, verbose_name='Quantidade TOTAL vendida'),
        ),
    ]
