# Generated by Django 4.0.1 on 2024-08-24 23:43

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilidades', '0022_produto_quantidade_total_vendida'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='lucro_atraves_desse_produto',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Lucro através desse produto'),
        ),
    ]
