# Generated by Django 4.0.1 on 2024-09-01 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0021_servico_tempo_de_duracao_minutos'),
        ('utilidades', '0024_promocao_produto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='tipo_do_produto',
        ),
        migrations.AddField(
            model_name='produto',
            name='tipo_do_produto',
            field=models.ManyToManyField(to='agendamentos.CategoriaDoServico', verbose_name='Tipo do produto'),
        ),
    ]
